name: Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://registry.terraform.io/github/webhook/Kagashino/cos-spa/tencentcloud
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
